language: php

php:
  - "5.5"

env:
  -WP_VERSION=master WP_MULTISITE=0

install:
  - nvm install 6.5.0
  - sudo apt-get install -y apache2

before_script:
  - cd /var/www
  - ls
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

  - sudo sed -i 's|/var/www/html|/var/www|g' /etc/apache2/sites-available/000-default.conf || true
  - sudo rm index.html
  - git clone https://github.com/WordPress/WordPress.git ./
  - ls
  - sudo service apache2 reload

  - ls
  - cd ./wp-content/plugins/
  - git clone https://github.com/Evarisk/Digirisk.git

script:
  - cd Digirisk/core/external/nightmare_js/
  - npm install nightmare
  - DEBUG=nightmare* node index.js

matrix:
  fast_finish: true
