language: php

php:
  - "5.5"

env:
  -WP_VERSION=master WP_MULTISITE=0

install:
  - nvm install 6.5.0
  - sudo apt-get install -y apache2

before_script:
  - cd /var/www
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  - sudo sed -i 's|/var/www/html|/var/www|g' /etc/apache2/sites-available/000-default.conf || true
  - sudo rm index.html
  - sudo git clone https://github.com/WordPress/WordPress.git /var/www
  - sudo service apache2 reload
  - sudo mkdir /var/www/wp-content/plugins/digirisk/
  - sudo git clone https://github.com/Evarisk/Digirisk.git /var/www/wp-content/plugins/digirisk/
  - cd /var/www/wp-content/plugins/digirisk/core/external/nightmare_js/
  - sudo -s
  - npm install nightmare

script:

  - sudo DEBUG=nightmare* node index.js

matrix:
  fast_finish: true
